// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NiriWindowId(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservationGeneration(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WirePath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SocketMode(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnixUserIdentifier(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemPrincipal(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Target(SystemTarget);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Focused(Boolean);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Generation(ObservationGeneration);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Backend(SystemBackend);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Kind(SubscriptionKind);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Health(SystemHealth);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Readiness(SystemReadiness);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Token(FocusSubscriptionToken);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Operation(SystemOperationKind);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Reason(SystemUnimplementedReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemSocketMode(SocketMode);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SupervisionSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SupervisionSocketMode(SocketMode);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SystemTarget {
    NiriWindow(NiriWindowId),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SystemBackend {
    Niri,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SubscriptionKind {
    Focus,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SystemHealth {
    Running,
    Degraded,
    Stopped,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SystemReadiness {
    Ready,
    Starting,
    Unavailable,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SystemOperationKind {
    WatchFocus,
    UnwatchFocus,
    QueryFocus,
    QueryStatus,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SystemUnimplementedReason {
    NotBuiltYet,
    BackendUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum OwnerIdentity {
    UnixUser(UnixUserIdentifier),
    System(SystemPrincipal),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FocusSubscription(Target);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FocusSubscriptionToken(Target);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FocusSnapshot(Target);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemStatusQuery(Backend);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FocusObservation {
    pub target: Target,
    pub focused: Focused,
    pub generation: Generation,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WindowClosed(Target);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionAccepted {
    pub target: Target,
    pub kind: Kind,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservationTargetMissing(Target);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemStatus {
    pub backend: Backend,
    pub health: Health,
    pub readiness: Readiness,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionRetracted(Token);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemRequestUnimplemented {
    pub operation: Operation,
    pub reason: Reason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SystemEvent {
    FocusObservation(FocusObservation),
    WindowClosed(WindowClosed),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemDaemonConfiguration {
    pub system_socket_path: SystemSocketPath,
    pub system_socket_mode: SystemSocketMode,
    pub supervision_socket_path: SupervisionSocketPath,
    pub supervision_socket_mode: SupervisionSocketMode,
    pub backend: Backend,
    pub owner_identity: OwnerIdentity,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    WatchFocus(FocusSubscription),
    UnwatchFocus(FocusSubscriptionToken),
    QueryFocus(FocusSnapshot),
    QueryStatus(SystemStatusQuery),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SubscriptionAccepted(SubscriptionAccepted),
    SubscriptionRetracted(SubscriptionRetracted),
    ObservationTargetMissing(ObservationTargetMissing),
    SystemStatus(SystemStatus),
    SystemRequestUnimplemented(SystemRequestUnimplemented),
    QueryFocusReply(FocusObservation),
    Event(SystemEvent),
}

#[rustfmt::skip]
impl NiriWindowId {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for NiriWindowId {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObservationGeneration {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for ObservationGeneration {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WirePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WirePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SocketMode {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SocketMode {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnixUserIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for UnixUserIdentifier {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SystemPrincipal {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SystemPrincipal {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Target {
    pub fn new(payload: SystemTarget) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SystemTarget {
        &self.0
    }
    pub fn into_payload(self) -> SystemTarget {
        self.0
    }
}
#[rustfmt::skip]
impl From<SystemTarget> for Target {
    fn from(payload: SystemTarget) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Focused {
    pub fn new(payload: Boolean) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Boolean {
        &self.0
    }
    pub fn into_payload(self) -> Boolean {
        self.0
    }
}
#[rustfmt::skip]
impl From<Boolean> for Focused {
    fn from(payload: Boolean) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Generation {
    pub fn new(payload: ObservationGeneration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObservationGeneration {
        &self.0
    }
    pub fn into_payload(self) -> ObservationGeneration {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObservationGeneration> for Generation {
    fn from(payload: ObservationGeneration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Backend {
    pub fn new(payload: SystemBackend) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SystemBackend {
        &self.0
    }
    pub fn into_payload(self) -> SystemBackend {
        self.0
    }
}
#[rustfmt::skip]
impl From<SystemBackend> for Backend {
    fn from(payload: SystemBackend) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Kind {
    pub fn new(payload: SubscriptionKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionKind {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionKind {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionKind> for Kind {
    fn from(payload: SubscriptionKind) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Health {
    pub fn new(payload: SystemHealth) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SystemHealth {
        &self.0
    }
    pub fn into_payload(self) -> SystemHealth {
        self.0
    }
}
#[rustfmt::skip]
impl From<SystemHealth> for Health {
    fn from(payload: SystemHealth) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Readiness {
    pub fn new(payload: SystemReadiness) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SystemReadiness {
        &self.0
    }
    pub fn into_payload(self) -> SystemReadiness {
        self.0
    }
}
#[rustfmt::skip]
impl From<SystemReadiness> for Readiness {
    fn from(payload: SystemReadiness) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Token {
    pub fn new(payload: FocusSubscriptionToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &FocusSubscriptionToken {
        &self.0
    }
    pub fn into_payload(self) -> FocusSubscriptionToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<FocusSubscriptionToken> for Token {
    fn from(payload: FocusSubscriptionToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Operation {
    pub fn new(payload: SystemOperationKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SystemOperationKind {
        &self.0
    }
    pub fn into_payload(self) -> SystemOperationKind {
        self.0
    }
}
#[rustfmt::skip]
impl From<SystemOperationKind> for Operation {
    fn from(payload: SystemOperationKind) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Reason {
    pub fn new(payload: SystemUnimplementedReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SystemUnimplementedReason {
        &self.0
    }
    pub fn into_payload(self) -> SystemUnimplementedReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<SystemUnimplementedReason> for Reason {
    fn from(payload: SystemUnimplementedReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SystemSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for SystemSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SystemSocketMode {
    pub fn new(payload: SocketMode) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SocketMode {
        &self.0
    }
    pub fn into_payload(self) -> SocketMode {
        self.0
    }
}
#[rustfmt::skip]
impl From<SocketMode> for SystemSocketMode {
    fn from(payload: SocketMode) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SupervisionSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for SupervisionSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SupervisionSocketMode {
    pub fn new(payload: SocketMode) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SocketMode {
        &self.0
    }
    pub fn into_payload(self) -> SocketMode {
        self.0
    }
}
#[rustfmt::skip]
impl From<SocketMode> for SupervisionSocketMode {
    fn from(payload: SocketMode) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FocusSubscription {
    pub fn new(payload: Target) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Target {
        &self.0
    }
    pub fn into_payload(self) -> Target {
        self.0
    }
}
#[rustfmt::skip]
impl From<Target> for FocusSubscription {
    fn from(payload: Target) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FocusSubscriptionToken {
    pub fn new(payload: Target) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Target {
        &self.0
    }
    pub fn into_payload(self) -> Target {
        self.0
    }
}
#[rustfmt::skip]
impl From<Target> for FocusSubscriptionToken {
    fn from(payload: Target) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FocusSnapshot {
    pub fn new(payload: Target) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Target {
        &self.0
    }
    pub fn into_payload(self) -> Target {
        self.0
    }
}
#[rustfmt::skip]
impl From<Target> for FocusSnapshot {
    fn from(payload: Target) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SystemStatusQuery {
    pub fn new(payload: Backend) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Backend {
        &self.0
    }
    pub fn into_payload(self) -> Backend {
        self.0
    }
}
#[rustfmt::skip]
impl From<Backend> for SystemStatusQuery {
    fn from(payload: Backend) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WindowClosed {
    pub fn new(payload: Target) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Target {
        &self.0
    }
    pub fn into_payload(self) -> Target {
        self.0
    }
}
#[rustfmt::skip]
impl From<Target> for WindowClosed {
    fn from(payload: Target) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObservationTargetMissing {
    pub fn new(payload: Target) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Target {
        &self.0
    }
    pub fn into_payload(self) -> Target {
        self.0
    }
}
#[rustfmt::skip]
impl From<Target> for ObservationTargetMissing {
    fn from(payload: Target) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubscriptionRetracted {
    pub fn new(payload: Token) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Token {
        &self.0
    }
    pub fn into_payload(self) -> Token {
        self.0
    }
}
#[rustfmt::skip]
impl From<Token> for SubscriptionRetracted {
    fn from(payload: Token) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SystemTarget {
    pub fn niri_window(payload: Integer) -> Self {
        Self::NiriWindow(NiriWindowId::new(payload))
    }
}

#[rustfmt::skip]
impl OwnerIdentity {
    pub fn unix_user(payload: Integer) -> Self {
        Self::UnixUser(UnixUserIdentifier::new(payload))
    }
    pub fn system(payload: String) -> Self {
        Self::System(SystemPrincipal::new(payload))
    }
}

#[rustfmt::skip]
impl SystemEvent {
    pub fn focus_observation(payload: FocusObservation) -> Self {
        Self::FocusObservation(payload)
    }
    pub fn window_closed(payload: Target) -> Self {
        Self::WindowClosed(WindowClosed::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn watch_focus(payload: Target) -> Self {
        Self::WatchFocus(FocusSubscription::new(payload))
    }
    pub fn unwatch_focus(payload: Target) -> Self {
        Self::UnwatchFocus(FocusSubscriptionToken::new(payload))
    }
    pub fn query_focus(payload: Target) -> Self {
        Self::QueryFocus(FocusSnapshot::new(payload))
    }
    pub fn query_status(payload: Backend) -> Self {
        Self::QueryStatus(SystemStatusQuery::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn subscription_accepted(payload: SubscriptionAccepted) -> Self {
        Self::SubscriptionAccepted(payload)
    }
    pub fn subscription_retracted(payload: Token) -> Self {
        Self::SubscriptionRetracted(SubscriptionRetracted::new(payload))
    }
    pub fn observation_target_missing(payload: Target) -> Self {
        Self::ObservationTargetMissing(ObservationTargetMissing::new(payload))
    }
    pub fn system_status(payload: SystemStatus) -> Self {
        Self::SystemStatus(payload)
    }
    pub fn system_request_unimplemented(payload: SystemRequestUnimplemented) -> Self {
        Self::SystemRequestUnimplemented(payload)
    }
    pub fn query_focus_reply(payload: FocusObservation) -> Self {
        Self::QueryFocusReply(payload)
    }
    pub fn event(payload: SystemEvent) -> Self {
        Self::Event(payload)
    }
}

#[rustfmt::skip]
impl From<NiriWindowId> for SystemTarget {
    fn from(payload: NiriWindowId) -> Self {
        Self::NiriWindow(payload)
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for OwnerIdentity {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::UnixUser(payload)
    }
}

#[rustfmt::skip]
impl From<SystemPrincipal> for OwnerIdentity {
    fn from(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<FocusObservation> for SystemEvent {
    fn from(payload: FocusObservation) -> Self {
        Self::FocusObservation(payload)
    }
}

#[rustfmt::skip]
impl From<WindowClosed> for SystemEvent {
    fn from(payload: WindowClosed) -> Self {
        Self::WindowClosed(payload)
    }
}

#[rustfmt::skip]
impl From<FocusSubscription> for Input {
    fn from(payload: FocusSubscription) -> Self {
        Self::WatchFocus(payload)
    }
}

#[rustfmt::skip]
impl From<FocusSubscriptionToken> for Input {
    fn from(payload: FocusSubscriptionToken) -> Self {
        Self::UnwatchFocus(payload)
    }
}

#[rustfmt::skip]
impl From<FocusSnapshot> for Input {
    fn from(payload: FocusSnapshot) -> Self {
        Self::QueryFocus(payload)
    }
}

#[rustfmt::skip]
impl From<SystemStatusQuery> for Input {
    fn from(payload: SystemStatusQuery) -> Self {
        Self::QueryStatus(payload)
    }
}

#[rustfmt::skip]
impl From<SubscriptionAccepted> for Output {
    fn from(payload: SubscriptionAccepted) -> Self {
        Self::SubscriptionAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<SubscriptionRetracted> for Output {
    fn from(payload: SubscriptionRetracted) -> Self {
        Self::SubscriptionRetracted(payload)
    }
}

#[rustfmt::skip]
impl From<ObservationTargetMissing> for Output {
    fn from(payload: ObservationTargetMissing) -> Self {
        Self::ObservationTargetMissing(payload)
    }
}

#[rustfmt::skip]
impl From<SystemStatus> for Output {
    fn from(payload: SystemStatus) -> Self {
        Self::SystemStatus(payload)
    }
}

#[rustfmt::skip]
impl From<SystemRequestUnimplemented> for Output {
    fn from(payload: SystemRequestUnimplemented) -> Self {
        Self::SystemRequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<FocusObservation> for Output {
    fn from(payload: FocusObservation) -> Self {
        Self::QueryFocusReply(payload)
    }
}

#[rustfmt::skip]
impl From<SystemEvent> for Output {
    fn from(payload: SystemEvent) -> Self {
        Self::Event(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_WATCH_FOCUS: u64 = 0x0000000000000000;
    pub const INPUT_UNWATCH_FOCUS: u64 = 0x0001000000000000;
    pub const INPUT_QUERY_FOCUS: u64 = 0x0002000000000000;
    pub const INPUT_QUERY_STATUS: u64 = 0x0003000000000000;
    pub const OUTPUT_SUBSCRIPTION_ACCEPTED: u64 = 0x0100000000000000;
    pub const OUTPUT_SUBSCRIPTION_RETRACTED: u64 = 0x0101000000000000;
    pub const OUTPUT_OBSERVATION_TARGET_MISSING: u64 = 0x0102000000000000;
    pub const OUTPUT_SYSTEM_STATUS: u64 = 0x0103000000000000;
    pub const OUTPUT_SYSTEM_REQUEST_UNIMPLEMENTED: u64 = 0x0104000000000000;
    pub const OUTPUT_QUERY_FOCUS_REPLY: u64 = 0x0105000000000000;
    pub const OUTPUT_EVENT: u64 = 0x0106000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    WatchFocus,
    UnwatchFocus,
    QueryFocus,
    QueryStatus,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    SubscriptionAccepted,
    SubscriptionRetracted,
    ObservationTargetMissing,
    SystemStatus,
    SystemRequestUnimplemented,
    QueryFocusReply,
    Event,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::WatchFocus(_) => InputRoute::WatchFocus,
            Self::UnwatchFocus(_) => InputRoute::UnwatchFocus,
            Self::QueryFocus(_) => InputRoute::QueryFocus,
            Self::QueryStatus(_) => InputRoute::QueryStatus,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::WatchFocus(_) => short_header::INPUT_WATCH_FOCUS,
            Self::UnwatchFocus(_) => short_header::INPUT_UNWATCH_FOCUS,
            Self::QueryFocus(_) => short_header::INPUT_QUERY_FOCUS,
            Self::QueryStatus(_) => short_header::INPUT_QUERY_STATUS,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_WATCH_FOCUS => Ok(InputRoute::WatchFocus),
            short_header::INPUT_UNWATCH_FOCUS => Ok(InputRoute::UnwatchFocus),
            short_header::INPUT_QUERY_FOCUS => Ok(InputRoute::QueryFocus),
            short_header::INPUT_QUERY_STATUS => Ok(InputRoute::QueryStatus),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::SubscriptionAccepted(_) => OutputRoute::SubscriptionAccepted,
            Self::SubscriptionRetracted(_) => OutputRoute::SubscriptionRetracted,
            Self::ObservationTargetMissing(_) => OutputRoute::ObservationTargetMissing,
            Self::SystemStatus(_) => OutputRoute::SystemStatus,
            Self::SystemRequestUnimplemented(_) => {
                OutputRoute::SystemRequestUnimplemented
            }
            Self::QueryFocusReply(_) => OutputRoute::QueryFocusReply,
            Self::Event(_) => OutputRoute::Event,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::SubscriptionAccepted(_) => short_header::OUTPUT_SUBSCRIPTION_ACCEPTED,
            Self::SubscriptionRetracted(_) => short_header::OUTPUT_SUBSCRIPTION_RETRACTED,
            Self::ObservationTargetMissing(_) => {
                short_header::OUTPUT_OBSERVATION_TARGET_MISSING
            }
            Self::SystemStatus(_) => short_header::OUTPUT_SYSTEM_STATUS,
            Self::SystemRequestUnimplemented(_) => {
                short_header::OUTPUT_SYSTEM_REQUEST_UNIMPLEMENTED
            }
            Self::QueryFocusReply(_) => short_header::OUTPUT_QUERY_FOCUS_REPLY,
            Self::Event(_) => short_header::OUTPUT_EVENT,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_SUBSCRIPTION_ACCEPTED => {
                Ok(OutputRoute::SubscriptionAccepted)
            }
            short_header::OUTPUT_SUBSCRIPTION_RETRACTED => {
                Ok(OutputRoute::SubscriptionRetracted)
            }
            short_header::OUTPUT_OBSERVATION_TARGET_MISSING => {
                Ok(OutputRoute::ObservationTargetMissing)
            }
            short_header::OUTPUT_SYSTEM_STATUS => Ok(OutputRoute::SystemStatus),
            short_header::OUTPUT_SYSTEM_REQUEST_UNIMPLEMENTED => {
                Ok(OutputRoute::SystemRequestUnimplemented)
            }
            short_header::OUTPUT_QUERY_FOCUS_REPLY => Ok(OutputRoute::QueryFocusReply),
            short_header::OUTPUT_EVENT => Ok(OutputRoute::Event),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "WatchFocus",
        "UnwatchFocus",
        "QueryFocus",
        "QueryStatus",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::StreamingFrame<Input, Output, SystemEvent>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::StreamingFrameBody<Input, Output, SystemEvent>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}

#[rustfmt::skip]
impl SystemEvent {
    pub fn into_subscription_frame(
        self,
        event_identifier: signal_frame::StreamEventIdentifier,
        token: signal_frame::SubscriptionTokenInner,
    ) -> Frame {
        Frame::with_short_header(
            signal_frame::ShortHeader::new(short_header::OUTPUT_EVENT),
            FrameBody::SubscriptionEvent {
                event_identifier,
                token,
                event: self,
            },
        )
    }
}
